### ISSUE TITLE
settings file is empty

### ISSUE THREAD

**Issue by yairEO** [fitnr/SublimeCSSTidy#23]
just installed on my sublime3 (on linux) and there is nothing in the configuration file.

Also, the README doesn't say anything about how to use this plugin. I have an open CSS file. now what should I do? Are there any keyboard shortcuts? it should be written in the README IMHO.

**Comment by fitnr** [comment]
The user settings file is always empty at first because of the way ST3 organizes things. Check out [csstidy.sublime-settings](https://github.com/fitnr/SublimeCSSTidy/blob/master/csstidy.sublime-settings) for a list of settings and explanation.

As explained in the second paragraph of the README, this plugin adds three commands to the command palette. You can access the palette by choosing Tools > Command Palette, or cmd-shift-P (on  OSX). Once the palette is open, start typing "Tidy CSS" and you'll see the CSSTidy's commands appear. select one by clicking on it or using the arrow keys and enter.

**Comment by yairEO** [comment]
I didn't not say anything about the user's settings file, which I am perfectly aware should be empty nor would I open an issue for such a thing. The Default settings are empty..
I think it's a sublime bug. it is a known thing with other packages also.
